server:
  port: 8081

spring:
  application:
    name: member-service

  # DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/member-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

# 로깅
logging:
  level:
    org.hibernate.type: trace

# 서비스 디스커버리
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/
#     defaultZone: http://eureka:8761/eureka/
