spring:
  application:
    name: gateway-service

server:
  port: 9000

# 서비스 디스커버리
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka:8761/eureka
      defaultZone: http://localhost:8761/eureka

# 액츄에이터
management:
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: routes, filters

# 라우팅
zuul:
  prefix: /api
